### ISSUE TITLE
Performance is better than in the paper

### ISSUE THREAD

**Issue by JindongGu** [neeeeenja/Tumor-CapsNet#1]
Hi there, Thanks for the awesome code! I try to run kfold.py code. Without modifying it, I got about averaged 90% accuracy, which is much better than the one reported in the paper (86,56).
Do you have any idea about this?

**Comment by changspencer** [comment]
Hey, thanks for bringing this up. I haven't touched this code in a long time, but I recently used the same dataset to complete a Master's thesis at Cal Poly.

### The Problem
When I programmed `prepareData`, I did not split the data based on a provided `cvind.mat` file that had all the fold numbers. So, if the sample is `1.mat` and the value at the first index is 1, then `1.mat` belongs to fold 1. I did not split folds based on this file.

This leads to an **information leak** from one fold to the next when doing K-fold cross-validation, because each patient's brain has multiple scans spread across the entire dataset. Thus, in one case, if you put half the scans in one fold and half in another fold, you could end up training the model with that particular brain, leading to higher accuracy when the model does validation. This is due to seeing similar data in training.

Let me know if you have any questions, and I will try to clarify.

**Comment by JindongGu** [comment]
Thanks for the clarification! Problem solved :)!
